[package]
name = "space_invaders"
version = "0.1.0"
authors = ["Vinicius Milani <vmrfreitas@inf.ufrgs.br>, Lucas Klein <lkdraghetti@inf.ufrgs.br>, Giovani Massiero <gmmalossi@inf.ufrgs.br>"]

[dependencies]
ggez = "0.4"
rand = "0.4"
